--- 
- hosts: dcos-cluster,dcos-bootstrap
  become: yes
  roles:
    - ansible-dcos-common
  tags:
    - common
    - ansible-dcos-common

- hosts: dcos-bootstrap
  roles:
    - ansible-dcos-bootstrap-node
  tags:
    - bootstrap
    - ansible-dcos-bootstrap-node
